### ISSUE TITLE
[Feature] Would it be possible to save OARs based on (x,y)-(x,y) coordinates?

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#149]
Hello,
I was wondering if it would be possible to add an ability to allow the server to save OARs of specific locations of a region such as saving a parcel/section of a large region using (x,y)-(x-y) coordinates?

**Comment by fly-man-** [comment]
I think an OAR files bases itself on a full region so I'm not sure if an OAR file would be the best thing for it.

**Comment by stormsonweathers** [comment]
Please correct me if I'm mistaken, but from what you wrote the process is do-able, but the OAR format may be a problem? Something more akin to creating a PAR (Parcel) file format for that purpose?

**Comment by fly-man-** [comment]
What I meant is that I have no idea if it's possible to make an OAR file of a specific parcel. The OAR format looks for everything on a region and saves that into a file.

However, I think that a PAR file would confuse the backend as you're unpacking only a piece of a region instead of a full part. The difficulties that I see are clashing parcel ID's, errors while placing objects

**Comment by stormsonweathers** [comment]
Got it! Thanks for clarifying.  I thought something like that could be a big help in backing up specific areas of regions such as parcels.
