### ISSUE TITLE
Search no longer returns results

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#155]
I have no clue when this happened but using the latest Firestorm and Singularity the Search no longer returns any results.

The only thing that I can see is that the query is being send to the Region / Grid server but it fails to return results.

**Comment by greythane** [comment]
This may have been caused by some recent updates that simplified a heap of modules.
Check your Config/Sim/Modules/WhiteCoreModules.ini and make sure you have the following... 
(line 180)

[Search]
SearchModule = SearchModule

There does appear to be a problem when searching for Events whilst using SQLite as the database, (to be investigated)

**Comment by fly-man-** [comment]
Indeed, looks like there were more things missing in the INI files for these servers.

I think it might be a good plan to have a Log info set for the modules so we can see if they are actively being triggered at Launchtime.

**Comment by fly-man-** [comment]
Issue closed due to the fact that Search returns accurate values now
