### ISSUE TITLE
Idea: no options for a hg to opensim

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#163]
Hello ;D

Hmm .. I was the first the user, the say pls make a option for the hg, so can jump to the opensim. But now, I know to build that the hg options in WCS is very difficult. So I will say, make WCS stable for the Users, make Physic Engine stable and the all fine options and make that we user can travel from WCS Grid to another Grid or Stdalone ;D 

I think that is more important as the hg options ;D

**Comment by greythane** [comment]
Thanks for the feedback...
BulletSim physics is in the process of being upgraded right now with results from the dev version being very gratifying... A partial update is available with the present dev code for testing with some additional tweaking and implementation 'in the works'.

The question of HyperGrid transport has always been on the agenda but initially, the native Inter World Connector will be fully implemented to allow 'joining' multiple grids together to appear as a large aggregate grid.  The plan here is to have all functionality transparent to the user/avatar.  This will mean that the current HG type of teleporting gates etc will not be necessary with multiple grids just appearing as one really large grid.
As to the implementation of the HyperGrid protocol as used in OpenSim, particularly due to the uncertainty of security and maintaining creator copyright etc. this does need further discussion.
