### ISSUE TITLE
Problem with change from mainland owner 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#171]
I have change the owner from the mainland estate, wcs change not the owner. I see this, when I see in the land info

http://bogus.as4u.de/privat/bilder/wcs/Bildschirmfoto_2015-12-08_19-03-21.png

I have no error messages in the console

**Comment by emperorstarfinder** [comment]
You might need reboot the region after changing the owner (assuming that you changed the region owner from Governor WhiteCore to your estate owner)  The reason here is that not all information will update immediately in-world when you are logged in because that information such as Estate Name, Estate Owner Name, Region Name, etc will not take effect until after the region is restarted so it will send the updated info back to the grid services and the viewer.

**Comment by BogusCurry** [comment]
mope, I have restart all services, no changes ..

**Comment by greythane** [comment]
Mainland regions are generally 'owned' by the 'Governor' and part of the 'Mainland Estate' group.
If you wish to change the owner's name you need to edit the appropriate ini file.

You need to update...
GovernorName = "Governor Whiter"
MainlandEstateName = "WhiteCore Mainland"

If you have a Grid setup:
Edit  Config\ServerConfiguration\Services.ini

For a Standalone setup:
Edit Config/Sim/StandAlone/StandAloneCommon.ini

These names can also be changed via a console command...
set estate name & set owner name 
Beware:  Names with (spaces) in them should be quoted if entered as a single command. (problems found, see below)
   i.e set estate name "WhiteCore Mainland" "My Mainland"
This is not necessary if using interactive entry mode.

(Thanks for this question as it uncovered a couple of 'funnies' when dealing with quoted parameters on the command line.... sorted in the latest commit)

**Comment by BogusCurry** [comment]
Hmm ... I will test it the fix ;D thanks for your support ;D

**Comment by greythane** [comment]
I think that by sorting out some Parcel  ownership problems, this has probably been corrected.
Updated code commit bf5fc7... on the 8th Feb 2016
