### ISSUE TITLE
Uploaded house is Green

### ISSUE THREAD

**Issue by MeeshaStormcrow** [WhiteCoreSim/WhiteCore-Dev#182]
When I upload my home, its is textured Green with "missing" all over it. A Fix?

**Comment by BogusCurry** [comment]
Is your house a mesh ? Created in Blender ?

**Comment by greythane** [comment]
Hi,
 If you are getting the green and red "missing" texture it means that the original texture used has not been uploaded with your house.
This is a "fallback" so that something is shown and can be easily identified when a requested asset is not available.
If you have saved your house as an IAR, the texture used may have been a system one which would not have been exported.  This may also happening the texture is flagged as no copy or no transfer.

**Comment by emperorstarfinder** [comment]
Easiest way to fix this if you get that due to the issues greythane has indicated is to upload the textures (if allowed to export them from another grid of course by the creator) and to apply them in-world onto the build in the usual way.
