### ISSUE TITLE
[question] Can WhiteCore-Sim use ipv6 IP-Adresses ? 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#193]
Hello ;D
More and more comes the the ipv6 IP-Adresses. So my question, can WhiteCore-Sim use the new Ip-Adress standard ?

Greetings

Bogus Curry

**Comment by emperorstarfinder** [comment]
WhiteCore still uses IPV4 currently.  IPV6 has not yet been tested in WhiteCore that I am aware and probably not yet implemented.

**Comment by fly-man-** [comment]
IPv6 hasn't been tested with WhiteCore mainly because most home users don't have a IPv6 address. The only problem with adding support for it is that for some people it will become a problem when IPv4 and IPv6 are being used cross through each other.

At this moment I don't see a direct reason to update with IPv6 but I will place this question on the Questions list on the Wiki
