### ISSUE TITLE
[Solve] Cannot open your terminal

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#203]
Hello all ;D

I have now pull to my grid the new commits and the grid run wonderful. But Now I can't open the screen for the console. I have make a screenshot ..

![bildschirmfoto_2016-05-24_12-56-22](https://cloud.githubusercontent.com/assets/614576/15501669/0b1c7fb4-21af-11e6-9b36-3b3406fee4ca.png)

What is wrong ?

Greetings
Bogus

**Comment by greythane** [comment]
Hi Bogus, 
This normally happens when you run screen as a different user than the one you have logged in as. Eg running the screen script via 'sudo su'
From your screen shot your user is whitesim. You should be able to login as this user, build WhiteCore using the 'autobuild.sh' and then copy the built WhiteCore by changing to the WhiteCoreSim directory and run via the 'run_gridmode.sh'....  all without changing users or using sudo Su.

$ ./autobuild.sh. >>. Multiple lines of output, a few warnings but no errors
$ cd WhiteCoreSim ( or wherever you opted this..)
$ ./run_gridmode.sh. > starting grid & sim servers messages
$ screen -r Grid. > for grid console
$ screen -r Sim. > for sim console

**Comment by BogusCurry** [comment]
yes and this to do, but the messages comes (Screenshot) when I will on the console with screen -r Grid. 

Local is all wounderful, on my server have I problems ..
