### ISSUE TITLE
Listen to port 20800

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#204]
Hi There ;D
I have pull the new changes to my testgrid and the gridserver run fine, but wenn I start the regionserver comes this 
Jun 15 10:16:02 - [XMLRPC]: Starting up XMLRPC Server on port 20800 for llRemoteData commands.
Jun 15 10:16:02 - [Base HTTP server]: Starting HTTP server on port 20800
Jun 15 10:16:02 - [Base HTTP server]: Error - Address already in use
Jun 15 10:16:02 - [Base HTTP server]: Tip: Do you have permission to listen on port 20800?

Is the XMLRPC SErver new and can change for my own the port or is that a bug ?

Greetings
Bogus

**Comment by greythane** [comment]
Hi Bogus, 
Thanks for checking out the updates, there are many and even though I have checked everything I can think of, quite possibly there are problems that have been missed.

The XMLrpc  port is an example :)
The reason for the error is that the port is being opened by the grid server and then later the region server is attempting to open the same port. This is something I have not yet been able to check as I am not sure if the XML stuff is grid or region specific. ( Prior to the updates, the Initialisation was being ignored)

If you have scripts etc that can check this out it would be appreciated.  It does appear that the XMLrpc commands are region related rather than grid and if so it is easy enough to specify which server actually opens and handles the XML commands.

**Comment by emperorstarfinder** [comment]
The XMLRPC calls were originally used for the region stuff and for groups i.e. Flotsam groups etc in opensim.  Aurora-Sim did use XMLRPC to an extent but I would have to go back and figure out what versions it did use.  It might even be worth while to see if we really even need those calls and if not just remove that?  Just a thought.

**Comment by greythane** [comment]
I have added a check for which instance is running before starting to xmlrpc server so this soils only be initialised by the region instance.

A quick check reveals that there are several lsl commands that do use these services so I will need to check into what their use is. It is possible that the calls could be made internal rather than via the external xml calls.

**Comment by BogusCurry** [comment]
Thanks greythane ;D I will test it ;D

**Comment by greythane** [comment]
Closing as this has now been corrected
