### ISSUE TITLE
Error load region

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#205]
Hello friend asked me to write uses your server since the last server upgrade, when loading regions gives this error http://prntscr.com/br3jqt But the server is running

**Comment by BogusCurry** [comment]
Hi ;D Which system use you ? Is a grid or a standalone ?

**Comment by emperorstarfinder** [comment]
This actually isn't related to a grid issue.  This is related to one of the LandData updates being out of range in the FileBasedSimulationData.  

1. Is the region a newly created region as of the latest master? 

2. Are you using the latest from the WhiteCore-Dev master?

**Comment by BogusCurry** [comment]
And which WhiteCoreSim version use you ?

**Comment by fly-man-** [comment]
I am more concerned about that other part I see down in the log file. Can you get the full log file as I see something I have seen with another customer but he had changed his ports.

Please attach a complete log file of the region so we can have a better look

**Comment by emperorstarfinder** [comment]
Okay after further testing it appears that the region file being read from on startup (as suggested by the console in the picture provided) is likely for a region created before the LandData updates.  If so that would in fact be why as that region file does not have some of the LandData stuff written in.  Newly created regions after the LandData Updates of July 5 appear to not have issues and appear to work as normal.

I am not directly aware of a port issue, usually if its a port issue i.e. two regions operating on the same port it would ask if you have permission to operate on that port etc. (at least that is what it should be doing)

**Comment by BogusCurry** [comment]
So I have pull the actualy version to my local testgrid and have no issues by login on my region.

**Comment by greythane** [comment]
Hi LifeGold,
The error you are getting is related to loading the terrain for the region for the 'sim' file.
I have seen this type of problem but only with very large regions where the terrain data gets 'corrupted'.

Can you let me know your region size please.
Also, if you check the RegionBak directory you will see previous snapshots of your region (date, time stamped), assuming this is not a new setup.  You ca try the following if you have backups available
Rename your existing region file i.e. Rai.sim  >> rai.simold or similar
Copy and rename a previous backup into the Region directory  
>> RegionBak/cp Rai--2016-07-01-11-29.sim (or as appropriate) to  Region/Rai.sim
Restart to see if the error persists.

If this is a new setup... can you let me know the region parameters you selected, particularly the terrain type.

Greythane

**Comment by greythane** [comment]
Closing as no responses received and issue could not be reproduced
