### ISSUE TITLE
Teleport error

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#206]
### Steps to reproduce

The next task is to teleport from one region to another when they are empty, no problem. To write for a long time, recorded the video for you. You should always try to teleport several times, only then it is possible. The same problem on the server and the virtual Universe. Was only thinking about the virtual Universe has decided to put the WhiteCore server to check the result is visible and this is all after the update in the regions where it was recently. 

https://www.youtube.com/watch?v=K4i3nVO_iqU&feature=youtu.be

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:**

**Database:**

**WhiteCore version: 0.9.4

### Logs

Please make sure that WhiteCore has made an log-file and include a link to it here

**Comment by BogusCurry** [comment]
Hello ;D your Video von youtube is private

**Comment by LifeGold** [comment]
Fixed

**Comment by emperorstarfinder** [comment]
It would appear that the server has notified the viewer of neighboring regions and has completed.  the timeout is probably related to a port not open on the server or in the host provider's network.

**Comment by LifeGold** [comment]
So you want to say that this year they were open and then closed without changing anything on the server, I repeat, when regions are empty he teleports from first time.

**Comment by emperorstarfinder** [comment]
So you want to say that this year they were open and then closed without changing anything on the server, I repeat, when regions are empty he teleports from first time.

So to answer this, essentially what I was intending to mean and say is we need to ensure these ports are open as at first glance of the video it appears there may be an issue with a callback timing out.  In many cases this is caused by a port being closed.  Ubuntu by default does not have a firewall enabled so it is likely not in the OS where this port may have been closed but rather by the network admin at the host provider in the network routers.

This is part of what is called the process of elimination which helps to rule out potential causes.

The next step if the ports are in fact opened for the region, we want to see debugging info.  This can be done by setting the log levels for both the Grid and Region console using the command set log level debug

Then try to teleport to the region.  This should help tell us more about what is going on for debugging purposes.  Remember some error messages will now show up while the consoles are set to log level info.

Also if you can provide further information as to what viewer your using? have you tried this with other viewers and gotten the same problem? etc.  This also helps to rule out potential causes.

**Comment by LifeGold** [comment]
The problem is already solved and the problem was not in the viewer, and not in the ports, for 2 hours under test works normally, if will work well, I will write here where and what to change in the source code.

**Comment by greythane** [comment]
Hi LifeGold,
I have seen this happen once or twice but never consistently like you have.
Please let me know what changes you made that corrected this problem.

Also, those OpenJpeg errors and warnings shown are being thrown by the Openmetaverse libraries and are related to problems decoding a texture.  The may be causing the timeout if the code is aborting before completion of a procedure but is not specifically related to teleporting

Greythane

**Comment by greythane** [comment]
LIfeGold,
I am really interested in what you did to correct this timeout error.
Is it possible to post details or just put you code on github  so I can check it out.

Greythane

**Comment by greythane** [comment]
No response received for additional details.
This condition does not appear to be reproducible or observed in general operations of existing systems.
