### ISSUE TITLE
Scripting problem

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#213]
### Steps to reproduce

1. Hi all the next question. The problem with the moving objects on the servers of OpenSim and second life scripts work fine, but on WhiteCoreSim and the virtual Universe. See for yourself, and so many scripts are not working. And I tried many different, not exactly the same.
https://www.youtube.com/watch?v=PaDaGo3gCQM&feature=youtu.be

### Server configuration

**Operating system**: Ubuntu 14.04

**WhiteCore version:** 0.9.4

**Comment by emperorstarfinder** [comment]
First off here, If you are using Virtual Universe please refer the problem to the Virtual Universe issue tracker as the WhiteCore-Sim Devs will not be able to assist you.

Second relating to the scripts.  Most scripts from Opensim and Secondlife including vehicle scripts (if not all) will work correctly.  In some cases you may need to make adjustments in the script itself to account for variations in how the scripting engine of the architecture handles the various functions.  Upon review of the video the problem appears to be more with needing to make adjustments in the script itself as opposed to an issue with the engine.

**Comment by LifeGold** [comment]
First, I used two servers and the VirtualUniverse and WhiteCoreSim - this problem is on both servers. Used more than 25 different patches of the scripts and still nothing has changed. You still think that the problem is in adjusting them, I would have said that 2 months ago they worked, but not now. If You are not sure that this is checked - take any script and check on the server.

**Comment by emperorstarfinder** [comment]
Okay let me clarify this.  You mention Virtual Universe here.  This issue tracker is only for WhiteCore-Sim.  If you find an issue with Virtual Universe you need to open the respective issue on the Virtual Universe Issue Tracker as the developers of WhiteCore-Sim cannot help you with issues relating to Virtual Universe.

Second I did not rule out that there is a problem in the script engine.  However the video itself would initially indicate a problem in the script itself.  Without info about errors if any are showing up on the consoles with it or having the actual script itself to test locally, it will be a bit harder to pin down the exact problem.  If you can provide additional details about errors showing up on the console (if any are showing up relating to the script) or provide a copy of the item so it can be tested to see if its able to be reproduced would be helpful.

Remember the more details and answering all the questions asked in the template provided when opening an issue provides a better chance of developers being able to fix the problem quicker.  That said if you can even provide a copy of the item in an IAR it will help even more because the item can be tested to see if the exact problem happens for someone else (i.e. a developer).

It should also be noted that there are some vehicle scripts that I am aware of from Opensim based regions that do act a bid oddly when it comes to using them in WhiteCore because the script engine in Opensim handles scripts very differently.

**Comment by LifeGold** [comment]
The console errors do not issue. Here is a link to IAR files https://github.com/LifeGold/iar
