### ISSUE TITLE
[Question] Which files are important for a backup ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#247]
Hi there ;D

I will make a backup from my grid and so my question which files was important for a backup ? 

Have a nice Day ;D

Bogus

**Comment by greythane** [comment]
Good question...
From your installation directory..

If you backup the entire 'Data' directory you will get most of the valid data.
This includes your region details, scripts, archives etc and also your assets if you are using the FileBased Asset system (the default) 

The rest of the required data is stored in (probably) the MySql database.
This contains user settings, inventory, groups etc so you will need to dump the entire database to an external file using mysqldump, phpadmin or a similar process so that it can be restored if required.  (I use Sequel Pro on the Mac)

NOTE: If you use additional installations for seperate grid connected regions etc you will need to backup each of the relevant Data directories.

The Config directory holds your current configuration setup so this one is probably a good idea to backup but not totally necessary as it can be re-configured from scratch.

All the rest of the scripts and directories are not really necessary as they can be reproduced...
e.g.: 'bin', '..docs', '*.sh' etc

**Comment by fly-man-** [comment]
It might be good to put this into the documents somewhere

* Putting it on the ToDo list

**Comment by greythane** [comment]
A 'How to' document has been drafted and will be available in the documents directory
