### ISSUE TITLE
Ownership of the loaded oars

### ISSUE THREAD

**Issue by toweiyg** [WhiteCoreSim/WhiteCore-Dev#268]
After i loaded an oar from the previous sim(Opensim0.7.6) to 0.9.5, I found the owner of the estate can not change the  settings of this region, such as forbidden erveryone has build rights.

This is weried, why the owner cannot modify the setting? And how to get the rights?

**Comment by greythane** [comment]
When an OAR is loaded, the owner of the assets etc are normally set to the estate owner of the region being updated.  This happens if the owner os the assets in the OAR cannot be found on the current system which will normally be the case is loading an OAR saved on an OpenSim instance.
(The owner account UUID's will be missing or different)

Note:  If the region is part of the mainland estate then the owner will be the 'Governor'.

**Comment by toweiyg** [comment]
Thank you @greythane , but how to solve this problem?

**Comment by emperorstarfinder** [comment]
I am unsure of what problem you are indicating your finding with WhiteCore-Sim itself.  However it is sounding like you ran into a problem when upgrading Opensimulator Version 0.7.6 to Opensimulator Version 0.9.5.  

As greythane has indicated when you load an OAR into your region on WhiteCore-Sim if the name and/ or UUID of the owner of the content (or region) does not exist then it will default to the region owner of your WhiteCore region.  In most (if not all cases) even if the name of the region owner or the owner of the content is the same in your WhiteCore-Sim instance the UUID is very much likely to be different in WhiteCore-Sim as opposed to Opensim.  This is why the ownership of the content will default to the region owner in WhiteCore-Sim so as not to cause unintended issues with loading the OAR and setting an owner of the content.

The only way to fix the UUID of the owner would be to know the UUID of each owner of the various content and update that user's UUID in your WhiteCore-Sim instance to match the UUID they were given in your Opensim instance.  This can be accomplished with the update user info command.  Otherwise there is really not much of a way to correct this.  If the user has not been created in your WhiteCore-Sim instances then you can input the right UUID from your Opensim database in which would give the user the matching UUID.  

Otherwise it appears to me that WhiteCore-Sim is handling loading the OAR the way it is intended to load the OAR.

**Comment by greythane** [comment]
Closing as answered
