### ISSUE TITLE
WhiteCore-Sim Dev Code broke with the actual Mono 5.x ?

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#277]
Hello all ;D
I have compile the actual version WhiteCore-Sim with the mono version...
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

Under Linux Ubuntu 16.04 x64, so I become as messages 
	 3 Warning(s)
	 3112 Error(s)

Whats going wrong ?

And yes I have make the compile script with sudo ;D

Have a nice Day ;D

Bogus Curry
Founder of GridTalk.de

**Comment by fly-man-** [comment]
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

After compiling: 
         9 Warning(s)
         0 Error(s)

Time Elapsed 00:02:04.7611280


So not sure what's happening on your side but it's compiling with the latest Mono 5. Did see some additional errors which are warnings but not the amount of error's you're getting

**Comment by greythane** [comment]
Hi Bogus,
A couple of things...
Have you  pulled in the LibOMV files as well?  If these are missing you will get a large number of errors.
From the main repo page...
NOTES:

- As of January 2017, the LibOMV libraries are included as a submodule of the WhiteCore repo. When cloning, ensure that the submodules are included.

git clone --recursive https://github.com/WhiteCoreSim/WhiteCore-Dev.git

To update an existing repository that does not have the LibOMV submodule

cd <your WhiteCore repository>
git submodule init
git submodule update

Also...
You do not need to be sudo to compile and run WhiteCore.  Building with root will cause problems later on due to file permissions.

G

**Comment by BogusCurry** [comment]
ahh yes, I have not libmov download .. ok I will check this .. sorry guys ;D

**Comment by BogusCurry** [comment]
Ok, was my fail all good ;D
