### ISSUE TITLE
Estate name default and where change it

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#284]
Hi, i need to know if in grid mode can change Estate name [Owner's Estate], file and path where change it or view it

Stay alert

**Comment by greythane** [comment]
Hi Johnfelipe,

For the system users and estate, check in Config/Grid/ServerConfiguration/Services.ini
Edit these before you startup otherwise restart if your grid is already running.
These settings are checked and appropriate modifications made at startup if required.
 
 ;;  Modify these if you want to change the name of a WhiteCore system user
 GovernorName = "Governor White"
 RealEstateOwnerName = "RealEstate Owner"
 BankerName = "WhiteCore Banker"
 MarketplaceOwnerName = "Marketplace Concierge"
   
 [EstateService]
 ;;  Modify these if you want to change the WhiteCore system Estate names
 MainlandEstateName = "Whitecore Mainland"
 SystemEstateName = "Whitecore Estate"
 
For a user Estate  you can use the `set estate name` command

**Comment by greythane** [comment]
Closing as answered
