### ISSUE TITLE
with GRANT or without GRANT

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#286]
I do all this with phpmyadmin with mysql 5.7
**NOT WORKING:**

> LOCALHOST

  **with** GRANT and **without** GRANT

![pantallazo-0211](https://user-images.githubusercontent.com/428820/27916263-2967238c-622e-11e7-80a5-9142b614a677.png)
Global and specific

![pantallazo-0212](https://user-images.githubusercontent.com/428820/27916291-3b0f17b6-622e-11e7-9c52-869e70879a1a.png)

show me this error:

> Jul 06 08:45:34 - [MySQL]: We cannot connect to the MySQL instance you have provided. Please make sure it is online, and then press enter to try again.

**WORKING**

> Server: **%**

![pantallazo-0213](https://user-images.githubusercontent.com/428820/27916542-feacf224-622e-11e7-81e7-13cfb7330a9d.png)

Then what is best option working server with % and with GRANT priviligies or without GRANT priviligies, AND global / specific or only global.

Stay alert

**Comment by emperorstarfinder** [comment]
If you are using the MySQL server in xampp, LAMP, LEMP, etc. even though it is running it will not work with WhiteCore.  You need to use the standalone MySQL or MariaDB server.  

Additionally you need to make sure ports for the DB server are open and that your pointing to the correct IP address of the server.

**Comment by johnfelipe** [comment]
I havent XAMPP, LAMP, LEMP, im using linux, look

http://200.122.209.133/phpinfo.php

I need to know GRANT or not GRANT (global/specific)

**Comment by emperorstarfinder** [comment]
ALways grant all permissions.  There is a script that handles the DB creation in the WhiteCoreHelpers folder.  Most general questions are easily answered in the documentation to.

**Comment by greythane** [comment]
To have any access to a database you need to grant permissions to a user.  As per EmperororStarfinder, for an sandboxed type of program like WhiteCore it is normally easier to grant all privileges rather than specific ones.  

The '%' is a modifier that tells MySql that access from all IP address's is allowed, however, most installations, unless modified, only allow access from the 'localhost' of the system IP address that the server is running on.  Unless the MySql server is running on a different system than your WhiteCore installation then the use of '%' is not needed for WhiteCore access.

- WhiteCore & MySql running on the same system
`	$mysql> CREATE USER 'whitecore'@'localhost' IDENTIFIED BY 'whitecorepass';
	$mysql> GRANT ALL PRIVILEGES ON whitecore.* TO whitecore@localhost IDENTIFIED BY 'whitecorepass';`

- Whitecore with MySql running on a seperate system
`	$mysql> CREATE USER 'whitecore'@'%' IDENTIFIED BY 'whitecorepass';
	$mysql> GRANT ALL PRIVILEGES ON whitecore.* TO 'whitecore'@'%' IDENTIFIED BY 'whitecorepass';`

The '% can also be replaced by a specific ip address if more security is required.
`	$mysql> CREATE USER 'whitecore'@'192.168.1.5' IDENTIFIED BY 'whitecorepass';
	$mysql> GRANT ALL PRIVILEGES ON whitecore.* TO 'whitecore'@'192.168.1.5' IDENTIFIED BY 'whitecorepass';`
In this case the MySql serve will grant access to the user 'white core' ONLY when accessed from the specified ip address.

**Comment by johnfelipe** [comment]
Is not working with localhost, pls test with lnmp shell script for install
all components, only works with %
Stay alert.

**Comment by emperorstarfinder** [comment]
Okay a couple of things here.

1. LNMP is a customized system similar to LEMP, LAMP, XAMPP, Etc.  these types of systems typically have secured the mysql database server already and have bound it to the IP detected on the server.  in which case because it has done the "secure_mysql_installation" command it has bound the IP to the machine.  Thus for any DB Username you create with your database to connect to your database server, you will need to rebind the IP in my.cnf to the external IP of the machine.  Then in your MySQL.ini in WhiteCore you need to specify the IP.  The only difference between LAMP and LNMP is LAMP uses the Apache server code where LNMP uses the NGINX server code for its web server.  So yes in fact your using a pre customized setup that your installing in linux which sets up the webserver, database server, PhpMyAdmin for the webui for the database administration, etc.  This is why you need to answer all the questions when opening a ticket.  This way we clear up any confusion at the outset.

2. What does "secure_mysql_installation" do exactly?: The "secure_mysql_installation" command secures your Database server.  When running a production level grid (where the general public can create accounts and login to the grid), it is always a wise idea to run this command.  This helps prevent hackers from hacking into the root useraccount on the server, prevents flooding of database tables and creation of fake database tables and information, blocks the creation of anonymous users, and closes some very bad back doors to the server.  Upon doing this command just like above you will have to edit the /etc/mysql/my.cnf file and changed the IP address that the server is bound to, so it will bind to the external IP of the machine the database server is on.  After you will need to restart the Database server for changes to take effect.  Then in the MySQL.ini file in WhiteCoreSim you will need to make sure the IP matches the the IP address of the database server.  

Your problem ultimately is because your WhiteCore instance is not able to connect to the database server.  What I have indicated above is the usual reason why.

**Comment by johnfelipe** [comment]
Pls give me exact commands, path and editions for continue my test. I need
review about my instance and do it perfectly for going production instance
in digitalocean
Stay alert commands and editions
Tnks so much for perfect support

**Comment by johnfelipe** [comment]
I can connect with %, but only error is this

Jul 05 08:39:28 - [LLogin service]: Login request for felipe urrego
from 190.251.131.150 with user agent Firestorm-Release 4.7.7.48706
starting in last
Jul 05 08:39:28 - [MySQL]: ExecuteNonQuery(DELETE FROM tokens WHERE (
((UNIX_TIMESTAMP(`validity`) - UNIX_TIMESTAMP()) <=
?where_lteqAND_1_UNIX_TIMESTAMP_validity_minus_UNIX_TIMESTAMP_))),
MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime
value: '1499288606'
  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00096] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32&
affectedRow, System.Int64& insertedId) [0x00026] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.Driver.GetResult (System.Int32
statementId, System.Int32& affectedRows, System.Int64& insertedId)
[0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.Driver.NextResult (System.Int32
statementId, System.Boolean force) [0x00023] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlDataReader.NextResult () [0x00205] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader
(System.Data.CommandBehavior behavior) [0x00315] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader () [0x00000] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00033]
in <0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery
(MySql.Data.MySqlClient.MySqlConnection connection, System.String
commandText, MySql.Data.MySqlClient.MySqlParameter[]
commandParameters) [0x00041] in <0a135c8e4d604d948724bf6960583b7f>:0
  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (System.String
connectionString, System.String commandText,
MySql.Data.MySqlClient.MySqlParameter[] parms) [0x0000d] in
<0a135c8e4d604d948724bf6960583b7f>:0
  at WhiteCore.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery
(System.String connStr, System.String sql,
System.Collections.Generic.Dictionary`2[TKey,TValue] parameters,
System.Boolean spamConsole) [0x00052] in
<8e239177980944678a0f544a3b549674>:0
Jul 05 08:39:28 - [LLLoginService]: User did not have a home, set to
04363519-1c12-438d-8b80-46a21a87f241
Jul 05 08:39:29 - [LLogin service]: All clear. Sending response to
client for login to region ebim1 at <128, 128, 25>.
WhiteCore.Server #

**Comment by emperorstarfinder** [comment]
If your actually able to log in and your able to move around and see the scene in-world then that error is a bit of a mystery and would be something that we would need to sort out but other then that you shouldn't have to much of a problem.

**Comment by greythane** [comment]
Hmm...  I am a little suspicious that you have opensim tables mixed up with WhiteCore ones.

The log... _MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime
value: '1499288606'_ appears to indicate the the 'validity' field expected a Daytime but in WhiteCore this field is an integer.. and the value is correct

Can you please verify that the structure of your **tokens** table is as shown below.
![screen shot 2017-07-07 at 4 45 03 pm](https://user-images.githubusercontent.com/4934735/27946157-c25e9cea-6333-11e7-88b5-ca8c72cf1a98.png)

**Comment by emperorstarfinder** [comment]
@greythane I ran a quick tet locally on a nix VM before I get some sleep just to be sure there isnt something we are missing here aside from the DB pieces which i think is part of these issues John has opened.  All appears normal from what I can tell.  However the only error that does come up that I can see is:

Estate owner name (/User Name) []: Emperor Starfinder
Do you want to 'park' the region with the system owner/estate? (yes/no) [yes]: enter

Jul 04 03:56:17 - [EVENT MANAGER]: Delegate for StartupComplete failed - continuing.  System.NullReferenceException: Object reference not set to an instance of an object
  at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0    at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0
Jul 04 03:56:17 - [WebUtils] Request failed - (URI:SyncMessageServerURI, METHOD:POST) : The request URI must either be an absolute URI or BaseAddress must be set
Jul 04 03:56:17 - [SceneManager]: Startup Complete. This took 0m 45.813s

I am going to take a guess here and say this particular error might have something to do when attempting to add the new Grid Owner id as the estate owner of the first region.  However when restarting the grid it appears it is there and working correctly.  

Other then that I think the rest of John's errors are in fact related to his database configurations itself and not necessarily WC.

**Comment by johnfelipe** [comment]
@greythane look

![pantallazo-0217](https://user-images.githubusercontent.com/428820/28020312-897545ba-6549-11e7-8527-0cef6e90f721.png)

@emperorstarfinder all is working, with % GRANT and NOT GRANT, only show me that error, but i can teleport, i can upload OAR, but every time show error about "TIMESTAMP"

**Comment by greythane** [comment]
JohnFelipe,
I have been thinking on this and I'm starting to suspect we have a number formatting problem.
The details you have given are in Spanish so I assume that your systems are running with Spanish as the default language and formatting.
Is this correct?

**Comment by johnfelipe** [comment]
@greythane only in spanish is phpmyadmin, all rest is eng

**Comment by greythane** [comment]
Closing as a user appears to be able to log in correctly.
Also duplicated questions previously commented on
