### ISSUE TITLE
problem importing opensim iar to whitecore

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#290]
I have this

https://drive.google.com/open?id=0B5b2y2kCFpKoYjdZUENxMTh0N3c

i upload with this steps:

	screen -r Grid 

	WhiteCore.Server # load iar
	User Name <first last>:  []: felipe urrego
	IAR file to load (? for list):  [felipe_urrego.iar]: /home/felipe/WhiteCore-Dev/WhiteCoreSim/Data/elegantsuitopensim.iar
	Do you want to 'merge' this archive or 'create' a new folder 'IAR Import'? (merge/create) [create]:enter

![pantallazo-0238](https://user-images.githubusercontent.com/428820/28535086-a93fa55a-7068-11e7-981d-1f10b2eea71a.png)

Opensim default version
![pantallazo-0237](https://user-images.githubusercontent.com/428820/28535106-bfee1250-7068-11e7-909e-a497067b233b.png)

Imported version
![pantallazo-0236](https://user-images.githubusercontent.com/428820/28535098-b6d99bf8-7068-11e7-8de0-9ab77918cec5.png)

How solve this, is really hard work put and rezise all
Stay alert

**Comment by emperorstarfinder** [comment]
The iar you want to load needs to be in the UserArchives folder

**Comment by johnfelipe** [comment]
i do it like u say and same result, pls test with iar file, i put up of page link
Stay alert

**Comment by emperorstarfinder** [comment]
After a quick test the iar does in fact work.  as shown in the second picture there are pieces you will need to adjust and put in place in the whitecore version and then save the iar with the adjustments for WhiteCore.  Also it would appear you do have some animations missing in the ao.  

The only error i could find was on the backend in the j2kdecoder having some out of bounds errors but that isn't anything to be overly concerned about on your end.

**Comment by johnfelipe** [comment]
Pls put then opensim iar is not compatible for whitecoresim iar. Tnks

**Comment by emperorstarfinder** [comment]
Just because you have to move some objects around and fix attachment points when importing an IAR created in opensim to whitecore does not render the IAR from opensim as incompatible.  In fact you will find with many different grid architectures you will have to make adjustments for it to work properly as it is intended to on that architecture.  

Your IAR is compatible you just need to fix your attachment points and make sure you have every object in the right position. and then resave the IAR in each architecture you have it on.
