### ISSUE TITLE
Grid use rather then standalone

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#293]
Pls tell me about differences, pro and contra about use GRID setup
Stay alert

**Comment by emperorstarfinder** [comment]
Grid mode means your running a grid and likely have multiple users, regions, and events going on.

Standalone mode primarily is for those who are just using for their own personal means.  Content creators often will use a standalone setup or a sim on a stick style version because they are using it to create content for virtual worlds.

There really is not all that much difference except one is in standalone mode and the other is in grid mode.
