### ISSUE TITLE
[solved] build on a windows server 2016 with many erros

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#301]
Hello ;D
I would build WCS actualy repo on a windows server 2016, now I becomes this
https://paste.md-5.net/himokobonu.tex

net framework 4.7.1 installed

What going wrong ?

Greetings
Bogus | Pinguinsreisen.de

**Comment by fly-man-** [comment]
@BogusCurry Be sure to use the runprebuild vs2015.bat

The errors I see have to do with you trying to compile against VS2010 which we no longer support

**Comment by BogusCurry** [comment]
Ok, I have now use the another batch file for build, but it's come the same errors messages .. 

https://paste.md-5.net/sehemowilu.tex

**Comment by fly-man-** [comment]
It looks like you dont have a DotNET installed that the runprebuild recognizes. The errors that are coming up are related to it not finding the correct DotNet which will error out.

I personally haven't tested it on Windows 2016 Server yet.

**Comment by emperorstarfinder** [comment]
You need to have a minimum of VS2013 in order for compiling to work.

The runtimes you should have installed in order to ensure proper working on Windows Server 2016 are:

vc_redist2008 (x86 and x64)
vc_redist2010 (x86 and x64)
vc_redist2012 (x64 and x64)
vc_redist2013 (x86 and x64)
vc_redist2015 (x86 and x64)

You also need to make sure that it has .Net Framework 4.0 and 4.5.x installed.  Unlike Windows 10, the Windows Server Operating System does not always come with the latest .Net Frameworks installed i.e. .Net Framework 4.0, 4.5.0, 4.5.1, 4.5.2, 4.6, 4.6.1, etc.

It is easier to compile on your local Windows 10 machine and then transfer the built binary files to the Windows Server 2016 machine.  Just be sure the machine that you compile WhiteCore-Sim on is the same bit type as the machine where the Windows 2016 server operating system is on (i.e. x86 or x64).

**Comment by BogusCurry** [comment]
Wow .. that is very confused for me .. lol Ok then I would more on linux worked with wcs ;D

**Comment by emperorstarfinder** [comment]
If your running it as a grid then I would recommend using Linux as opposed to Windows.

It should be noted however I have tested WhiteCore-Sim on Windows Server 2016 x64 and it does work correctly.  I also compile locally on a local build machine and then transfer the built binary files (contained in the WhiteCoreSim directory) to the server machines.  That way your using less space and memory on the server machine.

**Comment by BogusCurry** [comment]
I like more Linux as Windows, worked so long years on the system with WhiteCoreSim ;D So know more over Linux as over the windowssystem. So is the linux the best for me ;D

Thanks for your anwers ;D

**Comment by greythane** [comment]
Hi Bogus,
I use Linux for running (and developing) WhiteCore and actually it has way less problems than Windows.   I am not aware of anything that works better on Windows than it does on Linux using Mono.

**Comment by BogusCurry** [comment]
Hi Greythane ;D
'The run under windows was only test, I like more as then wcs under linux as under windows ;D
