### ISSUE TITLE
[Feature Request] Moving the 20800 XMLRPC

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [WhiteCoreSim/WhiteCore-Dev#90]
Is it possible to let the XMLRPC service being handled by the Grid Server instead of individual Region Servers. on Setups behind Firewalls/VPN's this can cause issues especially if a port can only be opened onced through the firewall

**Comment by fly-man-** [comment]
As I said before in the IRC channel, there are some things that kinda need to "disappear" since Http-IN has more options then XMLRPC.

The reason that each region has it's own XMLRPC is from old days when there was no other way to get data send and received. Since we now support HTTP-IN which even allows you to build a service based server inside your grid, I think XMLRPC is obsolete

However, I am willing to have a look if there is a possibility to make something like a XMLRPC switchboard but that will always be a external module, not something that will fit inside the Core of Whitecore

**Comment by greythane** [comment]
The latest updates correct the XMLRPC server initialization with the actual port being defined in the 'modules.ini' configuration.

As to whether to drop these calls or not, several lsl commands do rely on the xmlrpc implementation but it will be investigated if these can be made as internal processes.
