### ISSUE TITLE
[Localization] Global Positions (Picks / Classifieds) are not handled correctly

### ISSUE THREAD

**Issue by fly-man-** [WhiteCoreSim/WhiteCore-Dev#94]
06:08 <Fly-man-> zz_greythane: I have found what's causing Picks and Classifieds to go WAY off scale
06:08 <Fly-man-> zz_greythane: It seems we save the values into the database like this:
06:09 <Fly-man-> ,"GlobalPos":[256016.0,256247.0,21.9753246307373]
06:09 <Fly-man-> And we read them like this
06:09 <Fly-man-> ,"GlobalPos":[2560160,2562470,219753246307373]
06:09 <Fly-man-> In other words, the . is being mishandled
06:09 <Fly-man-> making the set go way off scale

* Solution: Come up with a fix that reads the value correctly from the database

**Comment by fly-man-** [comment]
Pushing this to Future as we need to go through a lot of hoops to get localization for a lot of things inside Whitecore checked

**Comment by greythane** [comment]
Note:  This issue has only been observed when running on Windows using .Net.

After much delving, this problem is inherited in the LibOMV DeserializeJson() processing. 
Even though the positional data, GlobalPos (Vector3), is saved and read correctly from storage, it appears that Windows assumes that all Float/Single/Double values will be formatted in the locale of the running system.  This conversion appears to be in the System libraries and probably not fixable on the higher level (LibOMV.StructuredData) where the processing of Json data to Vector3 is performed.

A workaround is to save the positional data as strings and control the format conversion within the main application where the local is set as en_US (as per how it is saved in the database)

_Note:  This may effect retrieval of standard floats as well but this has not been confirmed yet_

**Comment by greythane** [comment]
'Work arounds' implemented by saving the data as strings rather than numbers in the JSON string.

Fly-Man-, please close this once you have checked it out and verified that it does correct the problems you are seeing.

**Comment by greythane** [comment]
Verified as now corrected.
